### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ririko5834** [DevSnowflake/quickmongo#10]
How can i create multiple mongodb collections in one database? I want to separate my data to categories.

**Comment by Snowflake107** [comment]
I think you are looking for **[Database#createModel](https://quickmongo.js.org/#/docs/main/master/class/Database?scrollTo=createModel)**.

# Example

```js
const db = new Database(url); // main db
const testdb = db.createModel("test");

testdb.set("something", 123); // saves in test collection
db.get("something"); // null
```

**Comment by ririko5834** [comment]
Thanks, can i also create db table? I used that before in quick.db

**Comment by udit2303** [comment]
> Thanks, can i also create db table? I used that before in quick.db

You're looking for [Database#createTable](https://quickmongo.js.org/#/docs/main/master/class/Database?scrollTo=table)
Although, this is deprecated. You can look at the docs [here](https://quickmongo.js.org/#/). I believe it will answer most of your questions.

**Comment by Snowflake107** [comment]
@ririko5834 `createModel` is similar to `table`

**Comment by ririko5834** [comment]
Ok, but why was table deprecated?

**Comment by Snowflake107** [comment]
`mongodb` is NoSQL Database and `table` isn't really a good way to express collections for it :)

Use `db.createModel` instead of `db.table`

**Comment by ririko5834** [comment]
ok, another question how can I change main collection name from json to custom name.

**Comment by Snowflake107** [comment]
```js
new Database("DATABASE_URL", "Collection", MongooseOptions)
```
