### ISSUE TITLE
TTL

### ISSUE THREAD

**Issue by wolfier74** [DevSnowflake/quickmongo#11]
How can i remove value from database after 30 days? I want to make text hosting service and data should be removed after 30 days from data creation.
I think that i should save date.now() to database and then checking.
Please send me example code

**Comment by Snowflake107** [comment]
Yes, it is possible to store data temporarily on mongodb with mongodb `TTL` feature. However, this is not implemented in **quickmongo** yet. You can use your "**I think that i should save date.now() to database and then checking.**" method. Save the current timestamp and your expiry date (you can also use `ms` timeout) and compare it in each request. If it exceeds the timeout (when someone calls it), simply delete data.

**Comment by wolfier74** [comment]
Thanks, can you please add TTL feature to quickmongo or send me example code?

**Comment by wolfier74** [comment]
Please add it when you will have time
