### ISSUE TITLE
Inefficient

### ISSUE THREAD

**Issue by Flam3rboy** [DevSnowflake/quickmongo#15]
Just like quick.db you are storing all data in a single document and getting/setting the whole document for each operation. You should use the advantage of MongoDB and store it in the appropriate format: collection -> document -> sub array.

**Comment by Flam3rboy** [comment]
in fact I did it the same way as you but after some time in production run into performance issues. Thats why I needed to use native mongodb client and later wrote my own ORM to improve the efficiency.
Cou could keep everything as is and only fetch the needed data not the whole table similar like:
https://www.npmjs.com/package/lambert-orm

**Comment by Snowflake107** [comment]
Yeah, just like `quick.db`, this package is targeted for beginners/newbies who want to migrate to `mongodb` but with `quick.db` environment.

But we will look into this issue later 😁

**Comment by Flam3rboy** [comment]
any updates? xD
