### ISSUE TITLE
DB can't Update Data

### ISSUE THREAD

**Issue by AlenSaito1** [DevSnowflake/quickmongo#21]
Db doesn't update data of existing keys. 
For example:

```TS
import { Database } from 'quick.mongo'
const db = new Database(uri)

db.on('ready', async () => {

//Setting a new key
await db.set('testJid@s.whatsapp.net', '100')

console.log(await db.get('testJid@s.whatsapp.net')) //It logs `100`

//now when after I update the data on an existing key

await db.add('testJid@s.whatsapp.net', 20)
console.log(await db.get('testJid@s.whatsapp.net')) //It still logs `100` 


})
```
Any solutions? Am I doing anything worn here/

**Comment by Snowflake107** [comment]
Hello, the package name in import should be `quickmongo` instead of `quick.mongo`

```js
//Setting a new key
await db.set('testJid@s.whatsapp.net', '100')
```

Here, you are creating a new data as a `string` so `db.add` would throw error here. Let me know if it isn't working ¯\_(ツ)_/¯

**Comment by AlenSaito1** [comment]
> Hello, the package name in import should be `quickmongo` instead of `quick.mongo`
> 
> ```js
> //Setting a new key
> await db.set('testJid@s.whatsapp.net', '100')
> ```
> 
> Here, you are creating a new data as a `string` so `db.add` would throw error here. Let me know if it isn't working ¯_(ツ)_/¯

Oh I'm really sorry I was kinda In a rush while creating this issue.


```
import { Database } from 'quick.mongo'
const db = new Database(uri)

db.on('ready', async () => {

//Setting a new key
await db.set('testJid@s.whatsapp.net', '100')

console.log(await db.get('testJid@s.whatsapp.net')) //It logs `100`

//now when after I update the data on an existing key

await db.add('testJid@s.whatsapp.net', 20)
console.log(await db.get('testJid@s.whatsapp.net')) //It still logs `100` 


})

**Comment by Snowflake107** [comment]
@AlenSaito1 if `db.add` is not working properly, can you manually try using `db.set`?

**Comment by AlenSaito1** [comment]
> @AlenSaito1 if `db.add` is not working properly, can you manually try using `db.set`? Because, for me, `db.add` is working

I did try it with `db.set`, same result

**Comment by Snowflake107** [comment]
will look into it soon 👍🏻

**Comment by AlenSaito1** [comment]
Thank you

**Comment by Lebyy** [comment]
I can re-produce this issue

**Comment by sanikava** [comment]
> 
> 
> Db doesn't update data of existing keys.
> For example:
> 
> ```ts
> import { Database } from 'quick.mongo'
> const db = new Database(uri)
> 
> db.on('ready', async () => {
> 
> //Setting a new key
> await db.set('testJid@s.whatsapp.net', '100')
> 
> console.log(await db.get('testJid@s.whatsapp.net')) //It logs `100`
> 
> //now when after I update the data on an existing key
> 
> await db.add('testJid@s.whatsapp.net', 20)
> console.log(await db.get('testJid@s.whatsapp.net')) //It still logs `100` 
> 
> 
> })
> ```
> 
> Any solutions? Am I doing anything worn here/

You did mistake you using quick.mongo

use quickmongo
import { Database } from 'quickmongo'

**Comment by lumap** [comment]
same issue here, also happens with db.push, but this one returns the whole god damn database as an object instead of just the property. A workaround is to do the following: 
```js
db.set("user.balance", await db.add("user.balance",100))
//or in the case of db.push bc that one is RLY weirdo
let h = await db.push("user.items",{ name: "sword", damage: "too much" })
db.set("user.items", h["user"]["items"])
```

**Comment by Sekai966** [comment]
@Snowflake107 when will it be on npm my project is totaly relying on it

**Comment by Snowflake107** [comment]
> @Snowflake107 when will it be on npm my project is totaly relying on it

when #26 is merged

**Comment by keannyooi** [comment]
> when #26 is merged
ETA on that?
