### ISSUE TITLE
Appreciation post

### ISSUE THREAD

**Issue by TentacleSama4254** [DevSnowflake/quickmongo#29]
![IMG_20210825_220450.jpg](https://user-images.githubusercontent.com/74726248/130830220-d9ed14c6-1153-442d-b6aa-87dfcbd61c21.jpg)

**Comment by sp-sketch** [comment]
LoL

**Comment by ASACHIT** [comment]
lol

**Comment by ItzMeRM** [comment]
epik

**Comment by lumi-nation** [comment]
Memes are epic

**Comment by sp-sketch** [comment]
One more meme please

**Comment by DevAndromeda** [comment]
😄

**Comment by sp-sketch** [comment]
😳😳

**Comment by sp-sketch** [comment]
One More @TentacleSama4254

**Comment by sp-sketch** [comment]
😳😳

**Comment by dheeraz15** [comment]
lol

**Comment by AviDoesDev** [comment]
ahahahahahhahhh

**Comment by falseCloud** [comment]
epic

**Comment by jnsp-vsc** [comment]
epic

**Comment by scientific-dev** [comment]
**The board meeting in the organization will be like:**

![image](https://user-images.githubusercontent.com/69678617/130832575-fb8d5751-9003-4833-8701-4bab1c59ef1a.png)

**Comment by sp-sketch** [comment]
Hahahahaha

**Comment by rhydderchc** [comment]
RIP **QuickMongo**.
You were our hero.

**Comment by sp-sketch** [comment]
@DevAndromeda btw are there any issues with quick mongoi didn't Faced Any errors with package 😳😳

**Comment by rhydderchc** [comment]
> @DevAndromeda btw are there any issues with quick mongo didn't Faced Any errors with package 😳😳

Not maintained anymore, biggest issue.

**Comment by sp-sketch** [comment]
Why

**Comment by sp-sketch** [comment]
😳😳

**Comment by MathInDOS** [comment]
lolol

**Comment by nvx0** [comment]
fixed
