### ISSUE TITLE
cannot connect to multiple dbs

### ISSUE THREAD

**Issue by f-ionn** [DevSnowflake/quickmongo#6]
I get `(node:1265) UnhandledPromiseRejectionWarning: MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections`

**Comment by reallyfionn** [comment]
I am doing  this via
const { Database } = require('quickmongo')
const db1 = new Database(url)
const db2 = new Database(url)

**Comment by reallyfionn** [comment]
Any update?

**Comment by Snowflake107** [comment]
@reallyfionn need to finalize this #7 😊

**Comment by Snowflake107** [comment]
@reallyfionn Can you try using **[this](https://github.com/Snowflake107/quickmongo/tree/supp-multi-db)**? We need to make sure everything's working 😕

Install using: `npm i Snowflake107/quickmongo#supp-multi-db`
Docs: **[https://quickmongo.js.org](https://quickmongo.js.org/mdb)**

**Comment by reallyfionn** [comment]
Sure, I'll update you later, as I am in school rn.

**Comment by reallyfionn** [comment]
@Snowflake107 Sorry for the wait, can confirm this works!

**Comment by reallyfionn** [comment]
When is this gonna be added?

**Comment by ririko5834** [comment]
This would be useful for me too

**Comment by ririko5834** [comment]
When this will be added @Snowflake107 I want to use it too

**Comment by Snowflake107** [comment]
@ririko5834 `npm i Snowflake107/quickmongo#supp-multi-db`

**Comment by ririko5834** [comment]
OK, but when it will be merged to master branch?

**Comment by Snowflake107** [comment]
don't know

**Comment by ririko5834** [comment]
Please add it to master ASAP. 🙏

**Comment by Snowflake107** [comment]
should work on v3.0.0
