### ISSUE TITLE
The package save the data but don't fetch it.

### ISSUE THREAD

**Issue by xLilEnD** [DevSnowflake/quickmongo#9]
![image](https://user-images.githubusercontent.com/71594218/97756673-f4274c00-1b03-11eb-81c9-0d739876d689.png)
Here you see the code working nice and no thing wrong so let's test it.
![image](https://user-images.githubusercontent.com/71594218/97756727-0e612a00-1b04-11eb-83e2-9f028a9c71b4.png)
![image](https://user-images.githubusercontent.com/71594218/97756772-246eea80-1b04-11eb-8b60-8539cac37ba3.png)
He said done and it's working and console no errors. 
![image](https://user-images.githubusercontent.com/71594218/97756480-9bf04a00-1b03-11eb-8613-7589ab08c7ad.png)
In mongodb it's stored so let's type `test` to see if bot fetching.
![image](https://user-images.githubusercontent.com/71594218/97756844-41a3b900-1b04-11eb-812c-57e32fd36989.png)
![image](https://user-images.githubusercontent.com/71594218/97756856-46686d00-1b04-11eb-915c-014db13f7143.png)
So bot don't fetching the data and no errors how can I fix this ?

**Comment by Snowflake107** [comment]
Please use `await` before `db.fetch` or `db.set`

**Comment by xLilEnD** [comment]
> Please use `await` before `db.fetch` or `db.set`

Thanks that's worked for me.

**Comment by Snowflake107** [comment]
> > Please use `await` before `db.fetch` or `db.set`
> 
> Thanks that's worked for me and does this package support array ?

Yes

**Comment by xLilEnD** [comment]
> > > Please use `await` before `db.fetch` or `db.set`
> > 
> > 
> > Thanks that's worked for me and does this package support array ?
> 
> Yes

Then how to use it ?
